postsubmits:
  bells17-org-test/prow-test:
  - name: job-config-postsubmit
    decorate: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
presubmits:
  bells17-org-test/prow-test:
  - name: job-config-presubmit
    always_run: true
    decorate: true
    skip_report: false
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
  - name: job-config-presubmit2
    always_run: true
    decorate: true
    skip_report: false
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
